<?php
$pageTitle='Blocked Slots';require_once 'includes_admin_header.php';$services=getServices();
if(isset($_GET['delete'])){$id=(int)$_GET['delete'];$pdo->prepare('DELETE FROM blocked_slots WHERE id=?')->execute([$id]);redirect('blocked_slots.php?success=Slot unblocked');}
if($_SERVER['REQUEST_METHOD']==='POST'){$serviceId=(int)$_POST['service_id'];$date=$_POST['block_date'];$start=$_POST['start_time'];$end=$_POST['end_time'];$reason=trim($_POST['reason']);$pdo->prepare('INSERT INTO blocked_slots(service_id,block_date,start_time,end_time,reason) VALUES(?,?,?,?,?)')->execute([$serviceId,$date,$start.':00',$end.':00',$reason]);redirect('blocked_slots.php?success=Slot blocked');}
$blocked=$pdo->query('SELECT bs.*,s.name service_name FROM blocked_slots bs JOIN services s ON s.id=bs.service_id ORDER BY bs.block_date DESC, bs.start_time DESC')->fetchAll();
?>
<div class="panel"><h2>Block a slot</h2><form method="POST" class="filters">
<select name="service_id"><?php foreach($services as $s): ?><option value="<?= $s['id'] ?>"><?= e($s['name']) ?></option><?php endforeach; ?></select><input type="date" name="block_date" min="<?= date('Y-m-d') ?>" value="<?= date('Y-m-d') ?>"><select name="start_time"><?php foreach(getTimeSlots('06:00','23:00',30) as $t): ?><option value="<?= $t ?>"><?= date('h:i A',strtotime($t)) ?></option><?php endforeach; ?></select><select name="end_time"><?php foreach(getTimeSlots('06:30','23:30',30) as $t): ?><option value="<?= $t ?>"><?= date('h:i A',strtotime($t)) ?></option><?php endforeach; ?></select><input name="reason" placeholder="Reason"><button>Block</button>
</form><table><thead><tr><th>Service</th><th>Date</th><th>Time</th><th>Reason</th><th>Action</th></tr></thead><tbody><?php foreach($blocked as $b): ?><tr><td><?= e($b['service_name']) ?></td><td><?= e($b['block_date']) ?></td><td><?= e(date('h:i A',strtotime($b['start_time']))) ?> - <?= e(date('h:i A',strtotime($b['end_time']))) ?></td><td><?= e($b['reason']) ?></td><td><a class="btn danger" data-confirm="Unblock this slot?" href="blocked_slots.php?delete=<?= $b['id'] ?>">Unblock</a></td></tr><?php endforeach; ?></tbody></table></div>
<?php require_once 'includes_admin_footer.php'; ?>
